import type { TradeCase } from "./domain";

export const mockTradeCases: TradeCase[] = [
  {
    id: "TC-2026-0001",
    title: "【輸入】SI 1000pcs 指図済み / INV 400pcs のみ発行（数量差異）",
    tradeType: "import",
    supplier: {
      id: "SUP-CHN-ACME",
      name: "ACME Components (Shenzhen)",
      country: "CN",
      contactEmail: "sales@acme-components.example",
    },
    customer: {
      id: "CUS-JP-KANSAI",
      name: "Kansai Trading Co., Ltd.",
      country: "JP",
      contactEmail: "procurement@kansai-trading.example",
    },
    products: [
      {
        id: "P-USB-CABLE-01",
        name: "USB-C Cable 1m (Black)",
        sku: "UC-1M-BK",
        quantityOrdered: 1000,
        quantityInstructed: 1000,
        quantityInvoiced: 400,
        unitPrice: 0.85,
        currency: "USD",
      },
    ],
    documents: [
      {
        id: "DOC-0001-SI",
        type: "SI",
        title: "Shipping Instruction (1000 pcs)",
        source: "internal",
        issuedAt: "2026-04-18T09:00:00.000Z",
        extracted: { siQuantity: 1000 },
      },
      {
        id: "DOC-0002-INV",
        type: "Invoice",
        title: "Commercial Invoice (400 pcs)",
        source: "supplier",
        issuedAt: "2026-04-20T03:10:00.000Z",
        receivedAt: "2026-04-20T04:05:00.000Z",
        extracted: { invoiceQuantity: 400 },
      },
    ],
    shipmentState: "shippingPending",
    incidents: [
      {
        id: "INC-0001",
        type: "invoiceQuantityMismatch",
        severity: "high",
        status: "open",
        summary: "SI(1000pcs)に対しINVが400pcs分のみ発行。残数量のINV/PL手配が必要。",
        detectedAt: "2026-04-20T04:10:00.000Z",
        relatedDocumentIds: ["DOC-0001-SI", "DOC-0002-INV"],
        details: { siQuantity: 1000, invoiceQuantity: 400 },
      },
      {
        id: "INC-0002",
        type: "missingDocument",
        severity: "medium",
        status: "open",
        summary: "PL/B/L 未着。出荷前の書類不足でステータスが止まっている可能性。",
        detectedAt: "2026-04-21T00:00:00.000Z",
      },
    ],
    timeline: [
      {
        id: "TL-0001",
        at: "2026-04-18T09:00:00.000Z",
        type: "documentReceived",
        message: "SI を作成（数量 1000pcs 指図）",
        relatedDocumentId: "DOC-0001-SI",
      },
      {
        id: "TL-0002",
        at: "2026-04-20T04:05:00.000Z",
        type: "documentReceived",
        message: "仕入先より INV 受領（400pcs）",
        relatedDocumentId: "DOC-0002-INV",
      },
      {
        id: "TL-0003",
        at: "2026-04-20T04:10:00.000Z",
        type: "incidentDetected",
        message: "INV 数量差異を検知（1000 → 400）",
        relatedIncidentId: "INC-0001",
      },
      {
        id: "TL-0004",
        at: "2026-04-21T00:00:00.000Z",
        type: "statusChanged",
        message: "出荷前（書類不足の可能性）",
        shipmentState: "shippingPending",
      },
    ],
    nextActions: [
      {
        id: "ACT-0001",
        type: "confirmQuantity",
        priority: "high",
        status: "proposed",
        title: "仕入先へ残数量(600pcs)のINV/PL発行可否を確認",
        description: "SI 1000pcs に対して INV 400pcs のみ。分納なのか、INVの再発行/追加発行が必要か確認する。",
        dueBy: "2026-05-08T03:00:00.000Z",
        suggestedMessage:
          "SIは1000pcsで指図済みですが、INVが400pcs分のみ発行されています。残り600pcsの出荷予定と、追加INV/PLの発行可否をご確認ください。",
      },
      {
        id: "ACT-0002",
        type: "requestDocument",
        priority: "medium",
        status: "proposed",
        title: "PL/B/L の見込みと発行予定日を確認",
        description: "出荷・通関の先読みのため、PL/B/L と ETA の確定状況を確認する。",
      },
    ],
    updatedAt: "2026-05-07T01:30:00.000Z",
    createdAt: "2026-04-18T08:55:00.000Z",
    supplierBehaviorHints: ["frequentPartialInvoice", "slowReply"],
    marginRiskHints: ["quantityShortage"],
  },
  {
    id: "TC-2026-0002",
    title: "【輸入】出荷済み / ETA 変更（Forwarder メールあり）",
    tradeType: "import",
    supplier: {
      id: "SUP-VNM-ORION",
      name: "Orion Plastics (HCMC)",
      country: "VN",
      contactEmail: "export@orion-plastics.example",
    },
    customer: {
      id: "CUS-JP-TOKYO",
      name: "Tokyo Retail Supplies",
      country: "JP",
      contactEmail: "logistics@tokyo-retail.example",
    },
    products: [
      {
        id: "P-TRAY-02",
        name: "Display Tray (Medium)",
        sku: "TR-MED",
        quantityOrdered: 2000,
        quantityInstructed: 2000,
        quantityInvoiced: 2000,
        unitPrice: 1.15,
        currency: "USD",
      },
    ],
    documents: [
      {
        id: "DOC-0101-BL",
        type: "BL",
        title: "B/L (Original) - BL#VN12345678",
        source: "forwarder",
        receivedAt: "2026-04-28T10:20:00.000Z",
        extracted: { blNumber: "VN12345678", vessel: "NORTH STAR", voyage: "NS0426" },
      },
      {
        id: "DOC-0102-FWDMAIL",
        type: "ForwarderMail",
        title: "Forwarder Update: ETA Revised",
        source: "forwarder",
        receivedAt: "2026-05-02T02:15:00.000Z",
        summary: "Port congestion により ETA が 5/6 → 5/10 に変更。",
        extracted: { eta: "2026-05-10T00:00:00.000Z" },
      },
    ],
    shipmentState: "inTransit",
    incidents: [
      {
        id: "INC-0101",
        type: "etaChanged",
        severity: "medium",
        status: "open",
        summary: "Forwarder 連絡により ETA が変更。納期影響の確認が必要。",
        detectedAt: "2026-05-02T02:16:00.000Z",
        relatedDocumentIds: ["DOC-0102-FWDMAIL"],
      },
    ],
    timeline: [
      {
        id: "TL-0101",
        at: "2026-04-27T06:00:00.000Z",
        type: "statusChanged",
        message: "出荷済み（船積完了）",
        shipmentState: "shipped",
      },
      {
        id: "TL-0102",
        at: "2026-04-28T10:20:00.000Z",
        type: "documentReceived",
        message: "Forwarder より B/L 受領",
        relatedDocumentId: "DOC-0101-BL",
      },
      {
        id: "TL-0103",
        at: "2026-05-02T02:15:00.000Z",
        type: "emailReceived",
        message: "Forwarder メール受領：ETA 改定",
        relatedDocumentId: "DOC-0102-FWDMAIL",
      },
      {
        id: "TL-0104",
        at: "2026-05-02T02:16:00.000Z",
        type: "incidentDetected",
        message: "ETA変更を検知（5/6 → 5/10）",
        relatedIncidentId: "INC-0101",
      },
      {
        id: "TL-0105",
        at: "2026-05-02T02:20:00.000Z",
        type: "statusChanged",
        message: "輸送中",
        shipmentState: "inTransit",
      },
    ],
    nextActions: [
      {
        id: "ACT-0101",
        type: "updateEta",
        priority: "high",
        status: "proposed",
        title: "顧客へ ETA 変更連絡（必要なら納期調整）",
        description: "ETA 変更に伴う納期影響を確認し、必要に応じて顧客へ連絡する。",
        suggestedMessage:
          "Forwarderより連絡があり、港混雑の影響でETAが 2026-05-10 に変更となりました。販売/納品計画への影響があれば調整します。",
      },
      {
        id: "ACT-0102",
        type: "followUpForwarder",
        priority: "medium",
        status: "proposed",
        title: "遅延要因と追加費用の有無をForwarderに確認",
        description: "混雑起因の場合、D/Dや保管費等の追加費用が出る可能性があるため確認する。",
      },
    ],
    updatedAt: "2026-05-07T01:30:00.000Z",
    supplierBehaviorHints: ["stable"],
    marginRiskHints: ["freightIncrease", "unexpectedCharge"],
  },
  {
    id: "TC-2026-0003",
    title: "【三国間】通関完了 / 書類完備 / 正常に完了間近",
    tradeType: "triangular",
    supplier: {
      id: "SUP-TH-SIAM",
      name: "Siam Tools Co., Ltd.",
      country: "TH",
      contactEmail: "export@siam-tools.example",
    },
    customer: {
      id: "CUS-US-WEST",
      name: "West Coast Distribution Inc.",
      country: "US",
      contactEmail: "ops@westcoast-dist.example",
    },
    products: [
      {
        id: "P-TOOLKIT-07",
        name: "Hand Tool Kit (7pcs)",
        sku: "HTK-7",
        quantityOrdered: 300,
        quantityInstructed: 300,
        quantityInvoiced: 300,
        unitPrice: 18.4,
        currency: "USD",
      },
    ],
    documents: [
      {
        id: "DOC-0201-INV",
        type: "Invoice",
        title: "Commercial Invoice (300 sets)",
        source: "supplier",
        issuedAt: "2026-04-10T03:00:00.000Z",
        receivedAt: "2026-04-10T04:00:00.000Z",
        extracted: { invoiceQuantity: 300 },
      },
      {
        id: "DOC-0202-PL",
        type: "PackingList",
        title: "Packing List (300 sets)",
        source: "supplier",
        issuedAt: "2026-04-10T03:00:00.000Z",
        receivedAt: "2026-04-10T04:00:00.000Z",
      },
      {
        id: "DOC-0203-BL",
        type: "BL",
        title: "Sea Waybill - BL#TH99887766",
        source: "forwarder",
        receivedAt: "2026-04-12T08:30:00.000Z",
        extracted: { blNumber: "TH99887766", vessel: "EASTERN WIND", voyage: "EW0412" },
      },
      {
        id: "DOC-0204-AN",
        type: "ArrivalNotice",
        title: "Arrival Notice",
        source: "forwarder",
        receivedAt: "2026-04-26T01:10:00.000Z",
        extracted: { eta: "2026-04-26T00:00:00.000Z" },
      },
    ],
    shipmentState: "customsCleared",
    incidents: [],
    timeline: [
      {
        id: "TL-0201",
        at: "2026-04-10T04:00:00.000Z",
        type: "documentReceived",
        message: "INV/PL 受領（書類完備）",
        relatedDocumentId: "DOC-0201-INV",
      },
      {
        id: "TL-0202",
        at: "2026-04-12T08:30:00.000Z",
        type: "documentReceived",
        message: "B/L 受領",
        relatedDocumentId: "DOC-0203-BL",
      },
      {
        id: "TL-0203",
        at: "2026-04-26T01:10:00.000Z",
        type: "documentReceived",
        message: "Arrival Notice 受領",
        relatedDocumentId: "DOC-0204-AN",
      },
      {
        id: "TL-0204",
        at: "2026-04-26T02:00:00.000Z",
        type: "statusChanged",
        message: "入港",
        shipmentState: "arrived",
      },
      {
        id: "TL-0205",
        at: "2026-04-28T07:30:00.000Z",
        type: "statusChanged",
        message: "通関完了",
        shipmentState: "customsCleared",
      },
    ],
    nextActions: [
      {
        id: "ACT-0201",
        type: "other",
        priority: "low",
        status: "proposed",
        title: "最終納品確認・案件クローズ準備",
        description: "納品完了の確認後、案件を completed に更新する。",
      },
    ],
    updatedAt: "2026-05-06T23:30:00.000Z",
    supplierBehaviorHints: ["stable"],
  },
];
